fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ["--maxkb=2000"]
      - id: trailing-whitespace
      - id: check-merge-conflict

  # Allows for comments in json files
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5

  # Prettier: Primarily for markdown formatting
  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        entry: npx prettier@3.5.3 --write
        language: node
        types: [ javascript,ts,css,scss,less,html,json,markdown,yaml ]
        files: \.(js|jsx|ts|tsx|css|scss|less|html|json|md|ya?ml)$
