fail_fast: false

repos:
  - repo: builtin
    hooks:
      - id: end-of-file-fixer
        # all formatted files are excluded as oxfmt prefers inserting new line in empty toml files
        exclude: ^integration/fixtures/|.*\.(go|md|mdx|toml|ya?ml|jsx?|mjs|cjs|tsx?|jsonc?|css|star|pkl|sh)$
      - id: check-added-large-files
        args: ["--maxkb=2000"]
      - id: trailing-whitespace
        exclude: ^integration/fixtures/
      - id: check-merge-conflict
      # Allows for comments in json files
      - id: check-json5

  - repo: local
    hooks:
      - id: treefmt
        name: treefmt
        entry: treefmt
        language: system
