targets:
  - name: target_1
    command: "echo 'failed' && exit 1"
  - name: target_2
    command: ""
    dependencies:
      - :target_1
  - name: target_3
    command: "sleep 1 && echo 'this should run with --fail-fast=false'"
