targets:
  - name: target_1
    cmd: "echo 'failed' && exit 1"
  - name: target_2
    cmd: ""
    deps:
      - :target_1
  - name: target_3
    cmd: "sleep 0.1 && echo 'this should run with --fail-fast=false'"
