targets:
  - name: pex
    # Use the script file scripts/build_pex.sh as a tool
    command: $(bin //scripts:build_pex)
    dependencies:
      - //scripts:build_pex
      - //lib/format
    inputs:
      - main.py
      - server/**/*.py
    outputs: [ "dir::dist/" ]

  - name: image
    command: docker build -t server .
    dependencies:
      - :pex
    outputs:
      - docker::server

  - name: test
    command: uv run pytest
    dependencies:
      - //lib/format
    inputs:
      - server/**/*.py
      - tests/**/*.py
