targets:
  - name: venv
    inputs:
      - requirements.txt
    dependencies:
      - //src/protobuf:codegen_pip
    command: |
      rm -rf .venv
      python -m venv .venv
      source .venv/bin/activate
      pip install -r requirements.txt

  - name: python_test
    inputs:
      - "*.py"
    dependencies:
      - //src/protobuf:codegen
      - :venv
    command: |
      source .venv/bin/activate
      pytest
