targets:
  - name: codegen
    inputs:
      - "*.proto"
    command: |
      protoc --proto_path=. --go_out=pb --go-grpc_out=pb \
        --go_opt=paths=source_relative \
        --go-grpc_opt=paths=source_relative \
        --python_out=pb \
         *.proto
    outputs:
      - pb/person.pb.go
      - pb/person_pb2.py

  - name: codegen_pip
    inputs:
      - "**/*.py"
      - requirements.txt
      - setup.py
    command: "exit 0"
    dependencies:
      - :codegen
