targets:
  codegen:
    inputs:
      - "*.proto"
    cmd: |
      protoc --proto_path=. --go_out=pb --go-grpc_out=pb \
        --go_opt=paths=source_relative \
        --go-grpc_opt=paths=source_relative \
        --java_out=pb \
        --python_out=pb \
         *.proto
    outputs:
      - pb/person.pb.go
      - pb/person_pb2.py
      #- pb/com/examples/codegen/proto/PersonOuterClass.java

  codegen_pip:
    inputs:
      - "**/*.py"
      - requirements.txt
      - setup.py
    cmd: "exit 0"
    deps:
      - :codegen
