targets:
  - name: global_env
    command: |
      echo $FOO_VAR > global.txt
    outputs:
      - global.txt
    output_checks:
      - command: cat global.txt
        expected_output: "bar"
  - name: target_env
    environment_variables:
      BAZ_VAR: qux
    command: |
      echo $BAZ_VAR > target.txt
    outputs:
      - target.txt
    output_checks:
      - command: cat target.txt
        expected_output: "qux"
