targets:
  - name: dir_output
    inputs:
      - input.txt
    outputs:
      - dir::dist/ # Directory output containing generated files
    command: |
      rm -r dist
      mkdir -p dist
      echo "Hello World" > dist/file1.txt
      echo "Lorem ipsum" > dist/file2.txt

      cd dist
      # Confirm that symlinks work
      ln -s file1.txt file1-link.txt
