targets:
  - name: greet
    inputs:
      - "src/**/*.rs"
      - "Cargo.toml"
    dependency_resolvers: ["//:cargo"]
    dependencies:
      - //:workspace

  - name: build
    dependencies:
      - //:workspace
      - :greet
    command: cargo build -p greet --release

  - name: test
    dependencies:
      - //:workspace
      - :greet
    command: cargo test -p greet

  - name: clippy
    dependencies:
      - //:workspace
      - :greet
    command: cargo clippy -p greet --all-targets -- -D warnings
