targets:
  - name: server
    inputs:
      - "src/**/*.rs"
      - "Cargo.toml"
    dependency_providers: ["//:cargo"]
    dependencies:
      - //:workspace

  - name: build
    dependencies:
      - //:workspace
      - :server
    command: |
      cargo build -p server --release
      mkdir -p bin
      cp ../../target/release/server bin/server
    outputs:
      - bin/server

  - name: clippy
    dependencies:
      - //:workspace
      - :server
    command: cargo clippy -p server --all-targets -- -D warnings
