targets:
  - name: docker_output
    command: |
      docker build -t grog-hello-world .
    inputs:
      - script.sh
    outputs:
      - docker::grog-hello-world

  - name: remote_docker_output_succeeds
    command: |
      docker tag grog-hello-world us-central1-docker.pkg.dev/grog-457510/grog-cache/grog-hello-world
      docker push us-central1-docker.pkg.dev/grog-457510/grog-cache/grog-hello-world
    dependencies:
      - :docker_output
    outputs:
      - docker::us-central1-docker.pkg.dev/grog-457510/grog-cache/grog-hello-world
