targets:
  - name: build
    dependency_providers: ["//:cargo"]
    inputs:
      - "src/**/*.rs"
      - "Cargo.toml"
    dependencies:
      - //:workspace
    command: cargo build -p format --release

  - name: test
    inputs:
      - "src/**/*.rs"
      - "Cargo.toml"
    dependencies:
      - //:workspace
      - :build
    command: cargo test -p format

  - name: clippy
    inputs:
      - "src/**/*.rs"
      - "Cargo.toml"
    dependencies:
      - //:workspace
      - :build
    command: cargo clippy -p format --all-targets -- -D warnings
