targets:
  - name: build
    inputs:
      - "app/**/*.tsx"
      - "package.json"
    command: npm run build
    dependency_resolvers: ["//:node"]
    dependencies:
      - //:install
    outputs:
      - dir::.next/
