package main

import (
	"strings"
	"testing"

	"grog/internal/cmd"
)

func TestGenerateCLIDocument_IsDeterministic(t *testing.T) {
	firstDocument, err := generateCLIDocument(cmd.RootCmd)
	if err != nil {
		t.Fatalf("generate first CLI document: %v", err)
	}

	secondDocument, err := generateCLIDocument(cmd.RootCmd)
	if err != nil {
		t.Fatalf("generate second CLI document: %v", err)
	}

	if firstDocument != secondDocument {
		t.Fatal("expected generated CLI documents to be identical")
	}

	if !strings.Contains(firstDocument, "###### Auto generated by spf13/cobra\n") {
		t.Fatal("expected generated CLI document to contain deterministic footer")
	}
}
