package main

import (
	"bufio"
	"os"
	"sort"
	"strings"
	"testing"

	"grog/internal/cmd"
	"grog/internal/cmd/flagtypes"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

func TestGenerateCLIDocument_IsDeterministic(t *testing.T) {
	firstDocument, err := generateCLIDocument(cmd.RootCmd)
	if err != nil {
		t.Fatalf("generate first CLI document: %v", err)
	}

	secondDocument, err := generateCLIDocument(cmd.RootCmd)
	if err != nil {
		t.Fatalf("generate second CLI document: %v", err)
	}

	if firstDocument != secondDocument {
		t.Fatal("expected generated CLI documents to be identical")
	}

	if !strings.Contains(firstDocument, "###### Auto generated by spf13/cobra\n") {
		t.Fatal("expected generated CLI document to contain deterministic footer")
	}
}

// TestTopicCLIUsageMatchesCobra checks the formal grog usage signatures in the
// querying guide against the command tree. It intentionally does not inspect
// ordinary examples, which may contain shell syntax, variables, and pipelines.
func TestTopicCLIUsageMatchesCobra(t *testing.T) {
	path := "src/content/docs/topics/querying.mdx"
	file, err := os.Open(path)
	if err != nil {
		t.Fatalf("open %s: %v", path, err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	lineNumber := 0
	for scanner.Scan() {
		lineNumber++
		line := strings.TrimSpace(scanner.Text())
		if !strings.HasPrefix(line, "grog ") || (!strings.Contains(line, "[") && !strings.Contains(line, "<")) {
			continue
		}
		validateDocumentedUsage(t, path, lineNumber, line)
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("scan %s: %v", path, err)
	}
}

func validateDocumentedUsage(t *testing.T, path string, lineNumber int, usage string) {
	t.Helper()

	fields := strings.Fields(usage)
	command, _, err := cmd.RootCmd.Find([]string{fields[1]})
	if err != nil || command == cmd.RootCmd {
		t.Errorf("%s:%d: documented command %q does not exist", path, lineNumber, fields[1])
		return
	}

	documentedFlags := make(map[string]bool)
	minimumArguments := 0
	maximumArguments := 0
	for _, token := range fields[2:] {
		optional := strings.HasPrefix(token, "[")
		token = strings.Trim(token, "[]")
		if strings.HasPrefix(token, "--") {
			nameAndValue := strings.SplitN(strings.TrimPrefix(token, "--"), "=", 2)
			flag := command.Flags().Lookup(nameAndValue[0])
			if flag == nil {
				flag = command.InheritedFlags().Lookup(nameAndValue[0])
			}
			if flag == nil {
				t.Errorf("%s:%d: unknown flag --%s for %s", path, lineNumber, nameAndValue[0], command.CommandPath())
				continue
			}
			documentedFlags[nameAndValue[0]] = optional

			if len(nameAndValue) == 2 && strings.Contains(nameAndValue[1], "|") {
				documentedValues := strings.Split(nameAndValue[1], "|")
				enumValue, ok := flag.Value.(*flagtypes.Enum)
				if !ok {
					t.Errorf("%s:%d: --%s documents allowed values but is not an enum flag", path, lineNumber, nameAndValue[0])
					continue
				}
				allowedValues := append([]string(nil), enumValue.Allowed...)
				sort.Strings(documentedValues)
				sort.Strings(allowedValues)
				if strings.Join(documentedValues, "\x00") != strings.Join(allowedValues, "\x00") {
					t.Errorf("%s:%d: values for --%s are %v; Cobra metadata allows %v", path, lineNumber, nameAndValue[0], documentedValues, allowedValues)
				}
			}
			continue
		}

		maximumArguments++
		if !optional {
			minimumArguments++
		}
	}

	command.Flags().VisitAll(func(flag *pflag.Flag) {
		if _, required := flag.Annotations[cobra.BashCompOneRequiredFlag]; !required {
			return
		}
		optional, documented := documentedFlags[flag.Name]
		if !documented || optional {
			t.Errorf("%s:%d: required flag --%s is missing or documented as optional", path, lineNumber, flag.Name)
		}
	})

	for _, argumentCount := range []int{minimumArguments, maximumArguments} {
		if command.Args == nil {
			continue
		}
		arguments := make([]string, argumentCount)
		if err := command.Args(command, arguments); err != nil {
			t.Errorf("%s:%d: documented positional argument count %d is rejected by %s: %v", path, lineNumber, argumentCount, command.CommandPath(), err)
		}
	}
}
