package main

import (
	"bytes"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"grog/internal/cmd"

	"github.com/spf13/cobra"
)

const (
	outputDirectoryRelativePath = "src/content/docs/reference"
	outputFileName              = "commands.md"
)

func main() {
	outputDirectory := filepath.Join(docsDirectory(), outputDirectoryRelativePath)
	outputPath := filepath.Join(outputDirectory, outputFileName)

	if err := os.MkdirAll(outputDirectory, 0o755); err != nil {
		log.Fatalf("failed to create docs dir: %v", err)
	}

	if err := removeLegacyCommandDocs(outputDirectory, cmd.RootCmd.Name()); err != nil {
		log.Fatalf("failed to remove legacy docs: %v", err)
	}

	document, err := generateCLIDocument(cmd.RootCmd)
	if err != nil {
		log.Fatalf("failed to generate docs: %v", err)
	}

	if err := os.WriteFile(outputPath, []byte(document), 0o644); err != nil {
		log.Fatalf("failed to write docs: %v", err)
	}

	log.Println("Docs generated successfully.")
}

func docsDirectory() string {
	_, filename, _, ok := runtime.Caller(0)
	if !ok {
		log.Fatal("failed to determine docs generator path")
	}

	return filepath.Dir(filename)
}

func removeLegacyCommandDocs(directory string, rootCommandName string) error {
	legacyDirectory := filepath.Join(directory, "cli")
	if err := os.RemoveAll(legacyDirectory); err != nil {
		return fmt.Errorf("remove legacy directory %q: %w", legacyDirectory, err)
	}

	patterns := []string{
		filepath.Join(directory, rootCommandName+"*.md"),
		filepath.Join(directory, outputFileName),
	}

	for _, pattern := range patterns {
		matches, err := filepath.Glob(pattern)
		if err != nil {
			return fmt.Errorf("glob %q: %w", pattern, err)
		}

		for _, match := range matches {
			if err := os.Remove(match); err != nil && !os.IsNotExist(err) {
				return fmt.Errorf("remove %q: %w", match, err)
			}
		}
	}

	return nil
}

func generateCLIDocument(rootCommand *cobra.Command) (string, error) {
	commands := collectCommands(rootCommand)

	var builder strings.Builder
	builder.WriteString(`---
title: "CLI Commands"
sidebar:
  label: "Commands"
---
`)
	builder.WriteString("\n")
	builder.WriteString("Reference for the `grog` CLI.\n\n")
	builder.WriteString("## Commands\n\n")

	for _, command := range commands {
		fmt.Fprintf(&builder, "- [`%s`](#%s)\n", command.CommandPath(), commandAnchor(command))
	}

	builder.WriteString("\n")

	for index, command := range commands {
		section, err := renderCommandSection(command)
		if err != nil {
			return "", err
		}

		if index > 0 {
			builder.WriteString("\n---\n\n")
		}

		builder.WriteString(section)
		builder.WriteString("\n")
	}

	builder.WriteString("\n###### Auto generated by spf13/cobra\n")

	return builder.String(), nil
}

func collectCommands(rootCommand *cobra.Command) []*cobra.Command {
	var commands []*cobra.Command

	var visit func(command *cobra.Command)
	visit = func(command *cobra.Command) {
		commands = append(commands, command)

		children := visibleSubcommands(command)
		for _, child := range children {
			visit(child)
		}
	}

	visit(rootCommand)
	return commands
}

func visibleSubcommands(command *cobra.Command) []*cobra.Command {
	children := command.Commands()
	sort.Slice(children, func(leftIndex int, rightIndex int) bool {
		return children[leftIndex].Name() < children[rightIndex].Name()
	})

	var visible []*cobra.Command
	for _, child := range children {
		if !child.IsAvailableCommand() || child.IsAdditionalHelpTopicCommand() {
			continue
		}
		visible = append(visible, child)
	}

	return visible
}

func renderCommandSection(command *cobra.Command) (string, error) {
	command.InitDefaultHelpCmd()
	command.InitDefaultHelpFlag()

	var builder strings.Builder
	fmt.Fprintf(&builder, "## %s\n\n", command.CommandPath())
	if command.Short != "" {
		builder.WriteString(command.Short + "\n\n")
	}

	if len(command.Long) > 0 {
		builder.WriteString("### Synopsis\n\n")
		builder.WriteString(command.Long + "\n\n")
	}

	if command.Runnable() {
		fmt.Fprintf(&builder, "```text\n%s\n```\n\n", command.UseLine())
	}

	if len(command.Example) > 0 {
		builder.WriteString("### Examples\n\n")
		fmt.Fprintf(&builder, "```text\n%s\n```\n\n", command.Example)
	}

	if err := writeOptions(&builder, command); err != nil {
		return "", err
	}

	if hasRelatedCommands(command) {
		builder.WriteString("### See also\n\n")

		if command.HasParent() {
			parent := command.Parent()
			builder.WriteString(relatedCommandLine(parent))
		}

		for _, child := range visibleSubcommands(command) {
			builder.WriteString(relatedCommandLine(child))
		}

		builder.WriteString("\n")
	}

	return builder.String(), nil
}

func writeOptions(builder *strings.Builder, command *cobra.Command) error {
	nonInheritedFlags := command.NonInheritedFlags()
	if nonInheritedFlags.HasAvailableFlags() {
		var flagsBuffer bytes.Buffer
		nonInheritedFlags.SetOutput(&flagsBuffer)
		nonInheritedFlags.PrintDefaults()

		builder.WriteString("### Options\n\n")
		builder.WriteString("```text\n")
		builder.Write(flagsBuffer.Bytes())
		builder.WriteString("```\n\n")
	}

	inheritedFlags := command.InheritedFlags()
	if inheritedFlags.HasAvailableFlags() {
		var flagsBuffer bytes.Buffer
		inheritedFlags.SetOutput(&flagsBuffer)
		inheritedFlags.PrintDefaults()

		builder.WriteString("### Options inherited from parent commands\n\n")
		builder.WriteString("```text\n")
		builder.Write(flagsBuffer.Bytes())
		builder.WriteString("```\n\n")
	}

	return nil
}

func hasRelatedCommands(command *cobra.Command) bool {
	if command.HasParent() {
		return true
	}

	return len(visibleSubcommands(command)) > 0
}

func relatedCommandLine(command *cobra.Command) string {
	if command.Short == "" {
		return fmt.Sprintf("* [`%s`](#%s)\n", command.CommandPath(), commandAnchor(command))
	}

	return fmt.Sprintf("* [`%s`](#%s) - %s\n", command.CommandPath(), commandAnchor(command), command.Short)
}

func commandAnchor(command *cobra.Command) string {
	replacer := strings.NewReplacer(" ", "-", "_", "-", "/", "-")
	return strings.ToLower(replacer.Replace(command.CommandPath()))
}
