name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install dependencies
        run: |
          go mod tidy
          go install gotest.tools/gotestsum@latest

      - name: Install pkl
        run: |
          curl -L -o pkl-bin 'https://github.com/apple/pkl/releases/download/0.28.2/pkl-linux-amd64'
          chmod +x pkl-bin
          sudo mv pkl-bin /usr/local/bin/pkl

          pkl --version

      - name: Build and test
        #        env:
        #          REQUIRES_CREDS: ${{ github.ref == 'refs/heads/main' }}
        run: make test
#      - name: Upload coverage badge
#        if: github.ref == 'refs/heads/main'
#        run: |
#          .github/upload_badge.sh
#
